### ISSUE TITLE
Ayarlar ikonu taşıyor

### ISSUE THREAD

**Issue by kaan-gul** [KrmKayabasi/FrontendMentor_Pomodoro#1]
Ayarlar ikonu yukarı taşıyor.
Bir sonraki günceleme için boyutlandırmayı tekrar gözden geçirebilirsiniz yada ayarlar ikonunun yerini değiştirebilirsiniz.
![image](https://github.com/KrmKayabasi/FrontendMentor_Pomodoro/assets/97687364/36a429ed-ed1b-43b5-86d9-5d291df71325)

**Comment by KrmKayabasi** [comment]
Sorun son versiyon güncellemesiyle çözülmüştür. Destekleriniz için çok teşekkürler. İyi kullanmalar.
