### ISSUE TITLE
Klavye kısayolu ile mod değişimde buton text'i sabit kalıyor

### ISSUE THREAD

**Issue by kaan-gul** [KrmKayabasi/FrontendMentor_Pomodoro#2]
Örneğin "long break" modunda iken space ile sayacı başlatıp sağ veya sol tuşa basarak sayacı durdurmadan, çalışırken mod değiştirdiğimizde butonun altındaki "stop" yazısı "start" ile değişmesi gerekirken sabit kalıyor. Sadece tuşlar ile mod değiştirdiğimizde oluyor. Mouse ile tıklayarak mod değiştirdiğimizde problem olmadan stop yazısı start olarak güncelleniyor diğer moda geçince.

Aşağıdaki ekran resminde "stop" yazısı start olmalı fakat stop yazmaya devam ediyor butonda. Ancak iki kere space'e bastığımda ilk basışımda start yazısı geliyor. ve tekrar ikinci basışımda sayaç yeniden çalışmaya başlıyor. Umarım anlatabilmişimdir.
![image](https://github.com/KrmKayabasi/FrontendMentor_Pomodoro/assets/97687364/8e4456cb-5d7e-4ce7-a3d5-6c0a401ac0c1)

**Comment by KrmKayabasi** [comment]
Sorun son versiyon güncellemesiyle çözülmüştür. Destekleriniz için çok teşekkürler. İyi kullanmalar.
